global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask_api'
    static_configs:
      - targets: ['api:5000']
  
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka:9308']
  
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres:9187']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
